version: '3.8'

services:
  postgres:
    container_name: '${APP_NAME}_postgresql'
    image: postgres
    ports:
      - ${DATABASE_PORT}:5432
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
      POSTGRES_DB: ${DATABASE_NAME}
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres
