-- CreateEnum
CREATE TYPE "UserStatus" AS ENUM (
  'PENDING_VERIFICATION',
  'ACTIVE',
  'DEACTIVATED',
  'PERMANENTLY_DELETED'
);

-- AlterTable
ALTER TABLE "users"
ADD COLUMN "status" "UserStatus" NOT NULL DEFAULT 'PENDING_VERIFICATION';